### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by Fawesum** [bridgedxyz/base#22] opened 2021-05-02 14:49 UTC
I'm using this as intended by adding  "https://cors.bridged.cc/" in front of the image URLs, but sometimes it works and sometimes I get a 400 error saying "Missing required request header. Must specify one of: origin,x-requested-with"

**Comment by softmarshmallow** [comment] 2021-05-02 14:52
Hi. sorry for the inconvenience.


I must tell you nothing has changed since this febuary, system was running 24/7
I must take a look into the problem causing url.

can you give me a full working request url?

**Comment by Fawesum** [comment] 2021-05-02 18:09
Random image:

https://cors.bridged.cc/https://i1.wp.com/i.redd.it/xgxlv9ltd0a31.png?w=640&ssl=1

Gives the error, but the URL works fine at https://app.cors.bridged.cc/?method=GET&url=https://i1.wp.com&path=/i.redd.it/xgxlv9ltd0a31.png&params=%5B%7B%22key%22:%22w%22,%22value%22:%22640%22,%22active%22:true%7D,%7B%22key%22:%22ssl%22,%22value%22:%221%22,%22active%22:true%7D%5D

**Comment by softmarshmallow** [comment] 2021-05-06 03:42
Try with specifing one of `origin,x-requested-with` header with empty value.

**Comment by softmarshmallow** [comment] 2021-05-06 03:43
Might be duplicate of https://github.com/bridgedxyz/base/issues/21

**Closed** 2021-07-04 10:37 UTC
