### ISSUE TITLE
Response cookies

### ISSUE THREAD

**Issue by Lekhansh-dev** [bridgedxyz/base#26] opened 2021-06-03 06:24 UTC
Hi sir, 

Is there any way to get response cookies with the request?

**Comment by softmarshmallow** [comment] 2021-06-03 09:03
It does support cookie. but if you are using secure same domain cookie, that is impossible to work with - with-credentials
You'll need to host your own version

**Comment by Lekhansh-dev** [comment] 2021-06-03 09:40
can you explain me in detail?

**Comment by softmarshmallow** [comment] 2021-06-03 11:07
Well posting your example request will help a lot
via curl or app.cors.bridged.cc

**Comment by Lekhansh-dev** [comment] 2021-06-03 11:47
There is no cookies option like the postman.

Cors.bridged.cc - 
[https://i.imgur.com/cyIUlCK.png](url)

Postman - 
[https://i.imgur.com/tRScfFp.png](url)

**Comment by softmarshmallow** [comment] 2021-06-03 12:09
1. submit your working api call - without cors (with desired cookie behavior)
2. submit the non-working part of using cors.bridged.cc

ps. the cookie won't work on web browser api client. to test your cookie, you'll need to use desktop version of postman or insomnia

I cannot understand what you want to do or what the problem is with givven context

**Comment by Lekhansh-dev** [comment] 2021-06-03 13:15
Basically, I just wanna to get the response cookies.

Explanation - 
The response cookie is what the server provides after users sign in or signup on to the site
![Capture](https://user-images.githubusercontent.com/71216316/120650751-bb859180-c49b-11eb-99f7-d050f0aeb5be.PNG)
.

**Comment by softmarshmallow** [comment] 2021-06-03 13:20
If that cookie is used for storing user credentials, then it must not use any cors proxy.
If your trying to store some other insensitive data, then the localstorage is the right place.


1. if you are accessing 3rd party api - it won't use cookies
2. if you are using your own cookie with custom built server - you can add cors wildcard directly to your server's logic.
3. if you are using your own server, but just testing with non https environment, there is no way to do this.

But in general, you'll only store user credentials in secure cookie, which accessing via cors is now allowed.


Below comment is from cors-anywhere which bridged cors service uses.

> This package does not put any restrictions on the http methods or headers, except for cookies. Requesting user credentials is disallowed. The app can be configured to require a header for proxying a request, for example to avoid a direct visit from the browser.


I'm sorry that i cannot give you any clear response with cookie usage. - this is not meant to be used with cors proxy.

**Comment by Lekhansh-dev** [comment] 2021-06-03 14:09
I don't wanna store any cookies but I wanna get cookies from API. 

Without using cors.bridged.cc - 
![Capture](https://user-images.githubusercontent.com/71216316/120658309-ef17ea00-c4a2-11eb-9b60-2c80ad2abf61.PNG)
Using cors.bridged.cc - 
![Capture](https://user-images.githubusercontent.com/71216316/120658783-5df54300-c4a3-11eb-9306-fffda9aa26c7.PNG)

**Comment by junhoyeo** [comment] 2021-06-03 14:45
https://github.com/bridgedxyz/base/blob/e5b4d0d3bcc4a5974d7b7dcdac74b9f75473e82c/cors-service/lib/cors.ts#L98-L99
@Lekhansh-dev @softmarshmallow I think this behavior is caused by this line.
Code here deletes the `set-cookie` from the proxy response header. I patched this in PR #27.

**Comment by Lekhansh-dev** [comment] 2021-06-03 15:24
Ohh, Thanks btw

**Comment by softmarshmallow** [comment] 2021-06-03 16:06
Closing

**Closed by softmarshmallow** 2021-06-03 16:06 UTC
